# Generated by Django 5.2.8 on 2025-11-21 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('purchase_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchase_requests.purchaserequest'),
        ),
        migrations.AddField(
            model_name='approval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='purchase_requests.purchaserequest'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_requests.purchaserequest'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['organization', 'status'], name='purchase_re_organiz_3be552_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_by', 'status'], name='purchase_re_created_8b1dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='purchase_re_status_7d9b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['request', 'document_type'], name='purchase_re_request_641e01_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['request', 'approval_level'], name='purchase_re_request_f782e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('request', 'approval_level')},
        ),
    ]
